2023-10-08 09:31:36,258 - /Users/zhangmingming/pyProjects/vcrawl/vcrawl_task.py[line:25] - INFO: crawl type is darknet_trading_net,run_type is once
2023-10-08 10:44:58,400 - /Users/zhangmingming/pyProjects/vcrawl/vcrawl_task.py[line:25] - INFO: crawl type is darknet_trading_net,run_type is once
2023-10-08 10:46:29,152 - /Users/zhangmingming/pyProjects/vcrawl/vcrawl_task.py[line:26] - INFO: crawl type is darknet_trading_net,run_type is once
2023-10-08 10:46:43,096 - /Users/zhangmingming/pyProjects/vcrawl/vcrawl_task.py[line:41] - ERROR: once run error, error msg is 'id' , msgTraceback (most recent call last):
  File "/Users/zhangmingming/pyProjects/vcrawl/vcrawl_task.py", line 34, in run
    handler_list[key](jobconf).run(task_id)
  File "/Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py", line 328, in run
    self.task_id = kwargs['id']
KeyError: 'id'

2023-10-08 10:47:56,538 - /Users/zhangmingming/pyProjects/vcrawl/vcrawl_task.py[line:26] - INFO: crawl type is darknet_trading_net,run_type is once
2023-10-08 10:48:09,649 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:59] - INFO: jobconf=<tools.config_parser.CrawlConfigParser object at 0x7fad80a34250>
protocol=http
keywords=['建行', '建设银行', '银行', '信用卡', '贷款', '金融']
base_type=darknet
sub_type=trading_net
dtype=darknet_trading_net
alter_type=email
to_addrs=@163.com
error_addrs=zhangchaoss122@163.com
zh_type=暗网中文网
crux_key=
run_interval=1800
proxies={'http': 'socks5h://admin:a7dm1n@45.32.223.200:65533', 'https': 'socks5h://admin:a7dm1n@45.32.223.200:65533'}
tor_enable=False
tor_port=9151
username=759847
passwd=tianqi6997091
login_cookies_str_format=PHPSESSID=%s
query_cookies_str_format=PHPSESSID=%s; userid=%s
max_pagenum=20
domains=['xxxxxxxxss2wdceudprpxnmvjs5kwnlnfvun57koml6hkp6u7qwyhsyd.onion', 'xxxxxxxx3a3kuuhhw5w7stk25fzhttrlpiomij5bogkg7yyqsng5tqyd.onion', 'xxxxxxxxneal7wz6nk2tuquh54pruer5nfgwtsdw4c4xk6jc2swaidad.onion', 'xxxxxxxxp56bqacrnumb4ouvxthknazytrz4hsxhth4mjnm3kihdtoyd.onion', 'xxxxxxxzxxbmwmggbeyt26t6nlgktj5le7crh4yat6ztfwqxn4uxvmad.onion', 'xxxxxxxxqeuwvkrsesijvfcem4dtkpm77srgru2vrvk7dvm4hur3ymid.onion', 'deepmixaasic2p6vm6f4d4g52e4ve6t37ejtti4holhhkdsmq3jsf3id.onion', 'deepmixbf6xqt3m7kagmurdt4v43f2h3doc23h7hrkjlroovyjsvseqd.onion', 'deepmixjso4ero6h3psxskkb756offo3uznx4a44vuc5464mjkqwndyd.onion', 'deepmixl6jyyextuekqvufhaw3k4fv2zygcllo5lciupwdru6cb7xeqd.onion']
task_id=1
2023-10-08 10:48:10,269 - /Users/zhangmingming/pyProjects/vcrawl/tools/tor_tool.py[line:24] - INFO: reload tor
2023-10-08 10:48:10,274 - /Users/zhangmingming/pyProjects/vcrawl/tools/tor_tool.py[line:34] - ERROR: change ip error [Errno 61] Connection refused
2023-10-08 10:48:17,843 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:337] - INFO: parse domain is xxxxxxxxss2wdceudprpxnmvjs5kwnlnfvun57koml6hkp6u7qwyhsyd.onion, index_url is http://xxxxxxxxss2wdceudprpxnmvjs5kwnlnfvun57koml6hkp6u7qwyhsyd.onion
2023-10-08 10:48:17,844 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:88] - INFO: step1: request enter url
2023-10-08 10:48:17,845 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:86] - INFO: [GET METHOD] headers is : {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'xxxxxxxxss2wdceudprpxnmvjs5kwnlnfvun57koml6hkp6u7qwyhsyd.onion', 'Connection': 'keep-alive', 'Upgrade-Insecure-Requests': '1', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache'}
2023-10-08 10:48:17,845 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:87] - INFO: [GET METHOD] request url = http://xxxxxxxxss2wdceudprpxnmvjs5kwnlnfvun57koml6hkp6u7qwyhsyd.onion
2023-10-08 10:48:17,845 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:88] - INFO: [GET METHOD] request proxy = {'http': 'socks5h://admin:a7dm1n@45.32.223.200:65533', 'https': 'socks5h://admin:a7dm1n@45.32.223.200:65533'}
2023-10-08 10:48:17,845 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:89] - INFO: [GET METHOD] request params = None
2023-10-08 10:48:17,870 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:337] - INFO: parse domain is xxxxxxxx3a3kuuhhw5w7stk25fzhttrlpiomij5bogkg7yyqsng5tqyd.onion, index_url is http://xxxxxxxx3a3kuuhhw5w7stk25fzhttrlpiomij5bogkg7yyqsng5tqyd.onion
2023-10-08 10:48:17,871 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:88] - INFO: step1: request enter url
2023-10-08 10:48:17,871 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:86] - INFO: [GET METHOD] headers is : {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'xxxxxxxx3a3kuuhhw5w7stk25fzhttrlpiomij5bogkg7yyqsng5tqyd.onion', 'Connection': 'keep-alive', 'Upgrade-Insecure-Requests': '1', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache'}
2023-10-08 10:48:17,871 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:87] - INFO: [GET METHOD] request url = http://xxxxxxxx3a3kuuhhw5w7stk25fzhttrlpiomij5bogkg7yyqsng5tqyd.onion
2023-10-08 10:48:17,871 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:88] - INFO: [GET METHOD] request proxy = {'http': 'socks5h://admin:a7dm1n@45.32.223.200:65533', 'https': 'socks5h://admin:a7dm1n@45.32.223.200:65533'}
2023-10-08 10:48:17,871 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:89] - INFO: [GET METHOD] request params = None
2023-10-08 10:48:17,875 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:337] - INFO: parse domain is xxxxxxxxneal7wz6nk2tuquh54pruer5nfgwtsdw4c4xk6jc2swaidad.onion, index_url is http://xxxxxxxxneal7wz6nk2tuquh54pruer5nfgwtsdw4c4xk6jc2swaidad.onion
2023-10-08 10:48:17,875 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:88] - INFO: step1: request enter url
2023-10-08 10:48:17,875 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:86] - INFO: [GET METHOD] headers is : {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'xxxxxxxxneal7wz6nk2tuquh54pruer5nfgwtsdw4c4xk6jc2swaidad.onion', 'Connection': 'keep-alive', 'Upgrade-Insecure-Requests': '1', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache'}
2023-10-08 10:48:17,875 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:87] - INFO: [GET METHOD] request url = http://xxxxxxxxneal7wz6nk2tuquh54pruer5nfgwtsdw4c4xk6jc2swaidad.onion
2023-10-08 10:48:17,875 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:88] - INFO: [GET METHOD] request proxy = {'http': 'socks5h://admin:a7dm1n@45.32.223.200:65533', 'https': 'socks5h://admin:a7dm1n@45.32.223.200:65533'}
2023-10-08 10:48:17,875 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:89] - INFO: [GET METHOD] request params = None
2023-10-08 10:48:17,878 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:337] - INFO: parse domain is xxxxxxxxp56bqacrnumb4ouvxthknazytrz4hsxhth4mjnm3kihdtoyd.onion, index_url is http://xxxxxxxxp56bqacrnumb4ouvxthknazytrz4hsxhth4mjnm3kihdtoyd.onion
2023-10-08 10:48:17,879 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:88] - INFO: step1: request enter url
2023-10-08 10:48:17,879 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:86] - INFO: [GET METHOD] headers is : {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'xxxxxxxxp56bqacrnumb4ouvxthknazytrz4hsxhth4mjnm3kihdtoyd.onion', 'Connection': 'keep-alive', 'Upgrade-Insecure-Requests': '1', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache'}
2023-10-08 10:48:17,879 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:87] - INFO: [GET METHOD] request url = http://xxxxxxxxp56bqacrnumb4ouvxthknazytrz4hsxhth4mjnm3kihdtoyd.onion
2023-10-08 10:48:17,879 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:88] - INFO: [GET METHOD] request proxy = {'http': 'socks5h://admin:a7dm1n@45.32.223.200:65533', 'https': 'socks5h://admin:a7dm1n@45.32.223.200:65533'}
2023-10-08 10:48:17,879 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:89] - INFO: [GET METHOD] request params = None
2023-10-08 10:48:17,882 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:337] - INFO: parse domain is xxxxxxxzxxbmwmggbeyt26t6nlgktj5le7crh4yat6ztfwqxn4uxvmad.onion, index_url is http://xxxxxxxzxxbmwmggbeyt26t6nlgktj5le7crh4yat6ztfwqxn4uxvmad.onion
2023-10-08 10:48:17,882 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:88] - INFO: step1: request enter url
2023-10-08 10:48:17,883 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:86] - INFO: [GET METHOD] headers is : {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'xxxxxxxzxxbmwmggbeyt26t6nlgktj5le7crh4yat6ztfwqxn4uxvmad.onion', 'Connection': 'keep-alive', 'Upgrade-Insecure-Requests': '1', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache'}
2023-10-08 10:48:17,883 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:87] - INFO: [GET METHOD] request url = http://xxxxxxxzxxbmwmggbeyt26t6nlgktj5le7crh4yat6ztfwqxn4uxvmad.onion
2023-10-08 10:48:17,883 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:88] - INFO: [GET METHOD] request proxy = {'http': 'socks5h://admin:a7dm1n@45.32.223.200:65533', 'https': 'socks5h://admin:a7dm1n@45.32.223.200:65533'}
2023-10-08 10:48:17,883 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:89] - INFO: [GET METHOD] request params = None
2023-10-08 10:48:17,886 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:337] - INFO: parse domain is xxxxxxxxqeuwvkrsesijvfcem4dtkpm77srgru2vrvk7dvm4hur3ymid.onion, index_url is http://xxxxxxxxqeuwvkrsesijvfcem4dtkpm77srgru2vrvk7dvm4hur3ymid.onion
2023-10-08 10:48:17,886 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:88] - INFO: step1: request enter url
2023-10-08 10:48:17,886 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:86] - INFO: [GET METHOD] headers is : {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'xxxxxxxxqeuwvkrsesijvfcem4dtkpm77srgru2vrvk7dvm4hur3ymid.onion', 'Connection': 'keep-alive', 'Upgrade-Insecure-Requests': '1', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache'}
2023-10-08 10:48:17,886 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:87] - INFO: [GET METHOD] request url = http://xxxxxxxxqeuwvkrsesijvfcem4dtkpm77srgru2vrvk7dvm4hur3ymid.onion
2023-10-08 10:48:17,886 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:88] - INFO: [GET METHOD] request proxy = {'http': 'socks5h://admin:a7dm1n@45.32.223.200:65533', 'https': 'socks5h://admin:a7dm1n@45.32.223.200:65533'}
2023-10-08 10:48:17,886 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:89] - INFO: [GET METHOD] request params = None
2023-10-08 10:48:17,889 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:337] - INFO: parse domain is deepmixaasic2p6vm6f4d4g52e4ve6t37ejtti4holhhkdsmq3jsf3id.onion, index_url is http://deepmixaasic2p6vm6f4d4g52e4ve6t37ejtti4holhhkdsmq3jsf3id.onion
2023-10-08 10:48:17,889 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:88] - INFO: step1: request enter url
2023-10-08 10:48:17,889 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:86] - INFO: [GET METHOD] headers is : {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'deepmixaasic2p6vm6f4d4g52e4ve6t37ejtti4holhhkdsmq3jsf3id.onion', 'Connection': 'keep-alive', 'Upgrade-Insecure-Requests': '1', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache'}
2023-10-08 10:48:17,889 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:87] - INFO: [GET METHOD] request url = http://deepmixaasic2p6vm6f4d4g52e4ve6t37ejtti4holhhkdsmq3jsf3id.onion
2023-10-08 10:48:17,890 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:88] - INFO: [GET METHOD] request proxy = {'http': 'socks5h://admin:a7dm1n@45.32.223.200:65533', 'https': 'socks5h://admin:a7dm1n@45.32.223.200:65533'}
2023-10-08 10:48:17,890 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:89] - INFO: [GET METHOD] request params = None
2023-10-08 10:48:17,892 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:337] - INFO: parse domain is deepmixbf6xqt3m7kagmurdt4v43f2h3doc23h7hrkjlroovyjsvseqd.onion, index_url is http://deepmixbf6xqt3m7kagmurdt4v43f2h3doc23h7hrkjlroovyjsvseqd.onion
2023-10-08 10:48:17,892 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:88] - INFO: step1: request enter url
2023-10-08 10:48:17,893 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:86] - INFO: [GET METHOD] headers is : {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'deepmixbf6xqt3m7kagmurdt4v43f2h3doc23h7hrkjlroovyjsvseqd.onion', 'Connection': 'keep-alive', 'Upgrade-Insecure-Requests': '1', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache'}
2023-10-08 10:48:17,893 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:87] - INFO: [GET METHOD] request url = http://deepmixbf6xqt3m7kagmurdt4v43f2h3doc23h7hrkjlroovyjsvseqd.onion
2023-10-08 10:48:17,893 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:88] - INFO: [GET METHOD] request proxy = {'http': 'socks5h://admin:a7dm1n@45.32.223.200:65533', 'https': 'socks5h://admin:a7dm1n@45.32.223.200:65533'}
2023-10-08 10:48:17,893 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:89] - INFO: [GET METHOD] request params = None
2023-10-08 10:48:17,896 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:337] - INFO: parse domain is deepmixjso4ero6h3psxskkb756offo3uznx4a44vuc5464mjkqwndyd.onion, index_url is http://deepmixjso4ero6h3psxskkb756offo3uznx4a44vuc5464mjkqwndyd.onion
2023-10-08 10:48:17,896 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:88] - INFO: step1: request enter url
2023-10-08 10:48:17,896 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:86] - INFO: [GET METHOD] headers is : {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'deepmixjso4ero6h3psxskkb756offo3uznx4a44vuc5464mjkqwndyd.onion', 'Connection': 'keep-alive', 'Upgrade-Insecure-Requests': '1', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache'}
2023-10-08 10:48:17,896 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:87] - INFO: [GET METHOD] request url = http://deepmixjso4ero6h3psxskkb756offo3uznx4a44vuc5464mjkqwndyd.onion
2023-10-08 10:48:17,896 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:88] - INFO: [GET METHOD] request proxy = {'http': 'socks5h://admin:a7dm1n@45.32.223.200:65533', 'https': 'socks5h://admin:a7dm1n@45.32.223.200:65533'}
2023-10-08 10:48:17,896 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:89] - INFO: [GET METHOD] request params = None
2023-10-08 10:48:17,899 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:337] - INFO: parse domain is deepmixl6jyyextuekqvufhaw3k4fv2zygcllo5lciupwdru6cb7xeqd.onion, index_url is http://deepmixl6jyyextuekqvufhaw3k4fv2zygcllo5lciupwdru6cb7xeqd.onion
2023-10-08 10:48:17,899 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:88] - INFO: step1: request enter url
2023-10-08 10:48:17,899 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:86] - INFO: [GET METHOD] headers is : {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'deepmixl6jyyextuekqvufhaw3k4fv2zygcllo5lciupwdru6cb7xeqd.onion', 'Connection': 'keep-alive', 'Upgrade-Insecure-Requests': '1', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache'}
2023-10-08 10:48:17,899 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:87] - INFO: [GET METHOD] request url = http://deepmixl6jyyextuekqvufhaw3k4fv2zygcllo5lciupwdru6cb7xeqd.onion
2023-10-08 10:48:17,899 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:88] - INFO: [GET METHOD] request proxy = {'http': 'socks5h://admin:a7dm1n@45.32.223.200:65533', 'https': 'socks5h://admin:a7dm1n@45.32.223.200:65533'}
2023-10-08 10:48:17,899 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:89] - INFO: [GET METHOD] request params = None
2023-10-08 10:48:17,902 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:137] - ERROR: 暗网中文网爬虫错误,异常信息:["暗网中文网使用域名xxxxxxxxss2wdceudprpxnmvjs5kwnlnfvun57koml6hkp6u7qwyhsyd.onion错误,异常信息:SOCKSHTTPConnectionPool(host='xxxxxxxxss2wdceudprpxnmvjs5kwnlnfvun57koml6hkp6u7qwyhsyd.onion', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7fad405c7a10>: Failed to establish a new connection: [Errno 51] Network is unreachable'))", "暗网中文网使用域名xxxxxxxx3a3kuuhhw5w7stk25fzhttrlpiomij5bogkg7yyqsng5tqyd.onion错误,异常信息:SOCKSHTTPConnectionPool(host='xxxxxxxx3a3kuuhhw5w7stk25fzhttrlpiomij5bogkg7yyqsng5tqyd.onion', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7fad80fc0d50>: Failed to establish a new connection: [Errno 51] Network is unreachable'))", "暗网中文网使用域名xxxxxxxxneal7wz6nk2tuquh54pruer5nfgwtsdw4c4xk6jc2swaidad.onion错误,异常信息:SOCKSHTTPConnectionPool(host='xxxxxxxxneal7wz6nk2tuquh54pruer5nfgwtsdw4c4xk6jc2swaidad.onion', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7fad80fd3090>: Failed to establish a new connection: [Errno 51] Network is unreachable'))", "暗网中文网使用域名xxxxxxxxp56bqacrnumb4ouvxthknazytrz4hsxhth4mjnm3kihdtoyd.onion错误,异常信息:SOCKSHTTPConnectionPool(host='xxxxxxxxp56bqacrnumb4ouvxthknazytrz4hsxhth4mjnm3kihdtoyd.onion', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7fad80fc7b10>: Failed to establish a new connection: [Errno 51] Network is unreachable'))", "暗网中文网使用域名xxxxxxxzxxbmwmggbeyt26t6nlgktj5le7crh4yat6ztfwqxn4uxvmad.onion错误,异常信息:SOCKSHTTPConnectionPool(host='xxxxxxxzxxbmwmggbeyt26t6nlgktj5le7crh4yat6ztfwqxn4uxvmad.onion', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7fad405c7d50>: Failed to establish a new connection: [Errno 51] Network is unreachable'))", "暗网中文网使用域名xxxxxxxxqeuwvkrsesijvfcem4dtkpm77srgru2vrvk7dvm4hur3ymid.onion错误,异常信息:SOCKSHTTPConnectionPool(host='xxxxxxxxqeuwvkrsesijvfcem4dtkpm77srgru2vrvk7dvm4hur3ymid.onion', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7fad80fcd850>: Failed to establish a new connection: [Errno 51] Network is unreachable'))", "暗网中文网使用域名deepmixaasic2p6vm6f4d4g52e4ve6t37ejtti4holhhkdsmq3jsf3id.onion错误,异常信息:SOCKSHTTPConnectionPool(host='deepmixaasic2p6vm6f4d4g52e4ve6t37ejtti4holhhkdsmq3jsf3id.onion', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7fad80fdabd0>: Failed to establish a new connection: [Errno 51] Network is unreachable'))", "暗网中文网使用域名deepmixbf6xqt3m7kagmurdt4v43f2h3doc23h7hrkjlroovyjsvseqd.onion错误,异常信息:SOCKSHTTPConnectionPool(host='deepmixbf6xqt3m7kagmurdt4v43f2h3doc23h7hrkjlroovyjsvseqd.onion', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7fad80fda950>: Failed to establish a new connection: [Errno 51] Network is unreachable'))", "暗网中文网使用域名deepmixjso4ero6h3psxskkb756offo3uznx4a44vuc5464mjkqwndyd.onion错误,异常信息:SOCKSHTTPConnectionPool(host='deepmixjso4ero6h3psxskkb756offo3uznx4a44vuc5464mjkqwndyd.onion', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7fad80fcd590>: Failed to establish a new connection: [Errno 51] Network is unreachable'))", "暗网中文网使用域名deepmixl6jyyextuekqvufhaw3k4fv2zygcllo5lciupwdru6cb7xeqd.onion错误,异常信息:SOCKSHTTPConnectionPool(host='deepmixl6jyyextuekqvufhaw3k4fv2zygcllo5lciupwdru6cb7xeqd.onion', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7fad80fd3f10>: Failed to establish a new connection: [Errno 51] Network is unreachable'))"]
2023-10-08 10:49:03,539 - /Users/zhangmingming/pyProjects/vcrawl/vcrawl_task.py[line:26] - INFO: crawl type is darknet_trading_net,run_type is once
2023-10-08 10:49:03,541 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:59] - INFO: jobconf=<tools.config_parser.CrawlConfigParser object at 0x7f8e39ebdd50>
protocol=http
keywords=['建行', '建设银行', '银行', '信用卡', '贷款', '金融']
base_type=darknet
sub_type=trading_net
dtype=darknet_trading_net
alter_type=email
to_addrs=@163.com
error_addrs=zhangchaoss122@163.com
zh_type=暗网中文网
crux_key=
run_interval=1800
proxies={'http': 'socks5h://admin:a7dm1n@45.32.223.200:65533', 'https': 'socks5h://admin:a7dm1n@45.32.223.200:65533'}
tor_enable=False
tor_port=9151
username=759847
passwd=tianqi6997091
login_cookies_str_format=PHPSESSID=%s
query_cookies_str_format=PHPSESSID=%s; userid=%s
max_pagenum=20
domains=['xxxxxxxxss2wdceudprpxnmvjs5kwnlnfvun57koml6hkp6u7qwyhsyd.onion', 'xxxxxxxx3a3kuuhhw5w7stk25fzhttrlpiomij5bogkg7yyqsng5tqyd.onion', 'xxxxxxxxneal7wz6nk2tuquh54pruer5nfgwtsdw4c4xk6jc2swaidad.onion', 'xxxxxxxxp56bqacrnumb4ouvxthknazytrz4hsxhth4mjnm3kihdtoyd.onion', 'xxxxxxxzxxbmwmggbeyt26t6nlgktj5le7crh4yat6ztfwqxn4uxvmad.onion', 'xxxxxxxxqeuwvkrsesijvfcem4dtkpm77srgru2vrvk7dvm4hur3ymid.onion', 'deepmixaasic2p6vm6f4d4g52e4ve6t37ejtti4holhhkdsmq3jsf3id.onion', 'deepmixbf6xqt3m7kagmurdt4v43f2h3doc23h7hrkjlroovyjsvseqd.onion', 'deepmixjso4ero6h3psxskkb756offo3uznx4a44vuc5464mjkqwndyd.onion', 'deepmixl6jyyextuekqvufhaw3k4fv2zygcllo5lciupwdru6cb7xeqd.onion']
task_id=1
2023-10-08 10:49:03,541 - /Users/zhangmingming/pyProjects/vcrawl/tools/tor_tool.py[line:24] - INFO: reload tor
2023-10-08 10:49:03,544 - /Users/zhangmingming/pyProjects/vcrawl/tools/tor_tool.py[line:34] - ERROR: change ip error [Errno 61] Connection refused
2023-10-08 10:49:05,549 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:337] - INFO: parse domain is xxxxxxxxss2wdceudprpxnmvjs5kwnlnfvun57koml6hkp6u7qwyhsyd.onion, index_url is http://xxxxxxxxss2wdceudprpxnmvjs5kwnlnfvun57koml6hkp6u7qwyhsyd.onion
2023-10-08 10:49:05,553 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:88] - INFO: step1: request enter url
2023-10-08 10:49:05,553 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:86] - INFO: [GET METHOD] headers is : {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'xxxxxxxxss2wdceudprpxnmvjs5kwnlnfvun57koml6hkp6u7qwyhsyd.onion', 'Connection': 'keep-alive', 'Upgrade-Insecure-Requests': '1', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache'}
2023-10-08 10:49:05,554 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:87] - INFO: [GET METHOD] request url = http://xxxxxxxxss2wdceudprpxnmvjs5kwnlnfvun57koml6hkp6u7qwyhsyd.onion
2023-10-08 10:49:05,554 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:88] - INFO: [GET METHOD] request proxy = {'http': 'socks5h://admin:a7dm1n@45.32.223.200:65533', 'https': 'socks5h://admin:a7dm1n@45.32.223.200:65533'}
2023-10-08 10:49:05,554 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:89] - INFO: [GET METHOD] request params = None
2023-10-08 10:49:05,576 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:337] - INFO: parse domain is xxxxxxxx3a3kuuhhw5w7stk25fzhttrlpiomij5bogkg7yyqsng5tqyd.onion, index_url is http://xxxxxxxx3a3kuuhhw5w7stk25fzhttrlpiomij5bogkg7yyqsng5tqyd.onion
2023-10-08 10:49:05,577 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:88] - INFO: step1: request enter url
2023-10-08 10:49:05,577 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:86] - INFO: [GET METHOD] headers is : {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'xxxxxxxx3a3kuuhhw5w7stk25fzhttrlpiomij5bogkg7yyqsng5tqyd.onion', 'Connection': 'keep-alive', 'Upgrade-Insecure-Requests': '1', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache'}
2023-10-08 10:49:05,578 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:87] - INFO: [GET METHOD] request url = http://xxxxxxxx3a3kuuhhw5w7stk25fzhttrlpiomij5bogkg7yyqsng5tqyd.onion
2023-10-08 10:49:05,578 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:88] - INFO: [GET METHOD] request proxy = {'http': 'socks5h://admin:a7dm1n@45.32.223.200:65533', 'https': 'socks5h://admin:a7dm1n@45.32.223.200:65533'}
2023-10-08 10:49:05,578 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:89] - INFO: [GET METHOD] request params = None
2023-10-08 10:49:05,583 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:337] - INFO: parse domain is xxxxxxxxneal7wz6nk2tuquh54pruer5nfgwtsdw4c4xk6jc2swaidad.onion, index_url is http://xxxxxxxxneal7wz6nk2tuquh54pruer5nfgwtsdw4c4xk6jc2swaidad.onion
2023-10-08 10:49:05,583 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:88] - INFO: step1: request enter url
2023-10-08 10:49:05,584 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:86] - INFO: [GET METHOD] headers is : {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'xxxxxxxxneal7wz6nk2tuquh54pruer5nfgwtsdw4c4xk6jc2swaidad.onion', 'Connection': 'keep-alive', 'Upgrade-Insecure-Requests': '1', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache'}
2023-10-08 10:49:05,584 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:87] - INFO: [GET METHOD] request url = http://xxxxxxxxneal7wz6nk2tuquh54pruer5nfgwtsdw4c4xk6jc2swaidad.onion
2023-10-08 10:49:05,584 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:88] - INFO: [GET METHOD] request proxy = {'http': 'socks5h://admin:a7dm1n@45.32.223.200:65533', 'https': 'socks5h://admin:a7dm1n@45.32.223.200:65533'}
2023-10-08 10:49:05,584 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:89] - INFO: [GET METHOD] request params = None
2023-10-08 10:49:05,588 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:337] - INFO: parse domain is xxxxxxxxp56bqacrnumb4ouvxthknazytrz4hsxhth4mjnm3kihdtoyd.onion, index_url is http://xxxxxxxxp56bqacrnumb4ouvxthknazytrz4hsxhth4mjnm3kihdtoyd.onion
2023-10-08 10:49:05,589 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:88] - INFO: step1: request enter url
2023-10-08 10:49:05,589 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:86] - INFO: [GET METHOD] headers is : {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'xxxxxxxxp56bqacrnumb4ouvxthknazytrz4hsxhth4mjnm3kihdtoyd.onion', 'Connection': 'keep-alive', 'Upgrade-Insecure-Requests': '1', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache'}
2023-10-08 10:49:05,589 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:87] - INFO: [GET METHOD] request url = http://xxxxxxxxp56bqacrnumb4ouvxthknazytrz4hsxhth4mjnm3kihdtoyd.onion
2023-10-08 10:49:05,589 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:88] - INFO: [GET METHOD] request proxy = {'http': 'socks5h://admin:a7dm1n@45.32.223.200:65533', 'https': 'socks5h://admin:a7dm1n@45.32.223.200:65533'}
2023-10-08 10:49:05,589 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:89] - INFO: [GET METHOD] request params = None
2023-10-08 10:49:05,593 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:337] - INFO: parse domain is xxxxxxxzxxbmwmggbeyt26t6nlgktj5le7crh4yat6ztfwqxn4uxvmad.onion, index_url is http://xxxxxxxzxxbmwmggbeyt26t6nlgktj5le7crh4yat6ztfwqxn4uxvmad.onion
2023-10-08 10:49:05,594 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:88] - INFO: step1: request enter url
2023-10-08 10:49:05,594 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:86] - INFO: [GET METHOD] headers is : {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'xxxxxxxzxxbmwmggbeyt26t6nlgktj5le7crh4yat6ztfwqxn4uxvmad.onion', 'Connection': 'keep-alive', 'Upgrade-Insecure-Requests': '1', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache'}
2023-10-08 10:49:05,594 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:87] - INFO: [GET METHOD] request url = http://xxxxxxxzxxbmwmggbeyt26t6nlgktj5le7crh4yat6ztfwqxn4uxvmad.onion
2023-10-08 10:49:05,594 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:88] - INFO: [GET METHOD] request proxy = {'http': 'socks5h://admin:a7dm1n@45.32.223.200:65533', 'https': 'socks5h://admin:a7dm1n@45.32.223.200:65533'}
2023-10-08 10:49:05,594 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:89] - INFO: [GET METHOD] request params = None
2023-10-08 10:49:05,598 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:337] - INFO: parse domain is xxxxxxxxqeuwvkrsesijvfcem4dtkpm77srgru2vrvk7dvm4hur3ymid.onion, index_url is http://xxxxxxxxqeuwvkrsesijvfcem4dtkpm77srgru2vrvk7dvm4hur3ymid.onion
2023-10-08 10:49:05,598 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:88] - INFO: step1: request enter url
2023-10-08 10:49:05,598 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:86] - INFO: [GET METHOD] headers is : {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'xxxxxxxxqeuwvkrsesijvfcem4dtkpm77srgru2vrvk7dvm4hur3ymid.onion', 'Connection': 'keep-alive', 'Upgrade-Insecure-Requests': '1', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache'}
2023-10-08 10:49:05,598 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:87] - INFO: [GET METHOD] request url = http://xxxxxxxxqeuwvkrsesijvfcem4dtkpm77srgru2vrvk7dvm4hur3ymid.onion
2023-10-08 10:49:05,599 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:88] - INFO: [GET METHOD] request proxy = {'http': 'socks5h://admin:a7dm1n@45.32.223.200:65533', 'https': 'socks5h://admin:a7dm1n@45.32.223.200:65533'}
2023-10-08 10:49:05,599 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:89] - INFO: [GET METHOD] request params = None
2023-10-08 10:49:05,602 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:337] - INFO: parse domain is deepmixaasic2p6vm6f4d4g52e4ve6t37ejtti4holhhkdsmq3jsf3id.onion, index_url is http://deepmixaasic2p6vm6f4d4g52e4ve6t37ejtti4holhhkdsmq3jsf3id.onion
2023-10-08 10:49:05,602 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:88] - INFO: step1: request enter url
2023-10-08 10:49:05,602 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:86] - INFO: [GET METHOD] headers is : {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'deepmixaasic2p6vm6f4d4g52e4ve6t37ejtti4holhhkdsmq3jsf3id.onion', 'Connection': 'keep-alive', 'Upgrade-Insecure-Requests': '1', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache'}
2023-10-08 10:49:05,602 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:87] - INFO: [GET METHOD] request url = http://deepmixaasic2p6vm6f4d4g52e4ve6t37ejtti4holhhkdsmq3jsf3id.onion
2023-10-08 10:49:05,603 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:88] - INFO: [GET METHOD] request proxy = {'http': 'socks5h://admin:a7dm1n@45.32.223.200:65533', 'https': 'socks5h://admin:a7dm1n@45.32.223.200:65533'}
2023-10-08 10:49:05,603 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:89] - INFO: [GET METHOD] request params = None
2023-10-08 10:49:05,606 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:337] - INFO: parse domain is deepmixbf6xqt3m7kagmurdt4v43f2h3doc23h7hrkjlroovyjsvseqd.onion, index_url is http://deepmixbf6xqt3m7kagmurdt4v43f2h3doc23h7hrkjlroovyjsvseqd.onion
2023-10-08 10:49:05,606 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:88] - INFO: step1: request enter url
2023-10-08 10:49:05,606 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:86] - INFO: [GET METHOD] headers is : {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'deepmixbf6xqt3m7kagmurdt4v43f2h3doc23h7hrkjlroovyjsvseqd.onion', 'Connection': 'keep-alive', 'Upgrade-Insecure-Requests': '1', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache'}
2023-10-08 10:49:05,606 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:87] - INFO: [GET METHOD] request url = http://deepmixbf6xqt3m7kagmurdt4v43f2h3doc23h7hrkjlroovyjsvseqd.onion
2023-10-08 10:49:05,606 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:88] - INFO: [GET METHOD] request proxy = {'http': 'socks5h://admin:a7dm1n@45.32.223.200:65533', 'https': 'socks5h://admin:a7dm1n@45.32.223.200:65533'}
2023-10-08 10:49:05,606 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:89] - INFO: [GET METHOD] request params = None
2023-10-08 10:49:05,609 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:337] - INFO: parse domain is deepmixjso4ero6h3psxskkb756offo3uznx4a44vuc5464mjkqwndyd.onion, index_url is http://deepmixjso4ero6h3psxskkb756offo3uznx4a44vuc5464mjkqwndyd.onion
2023-10-08 10:49:05,610 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:88] - INFO: step1: request enter url
2023-10-08 10:49:05,610 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:86] - INFO: [GET METHOD] headers is : {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'deepmixjso4ero6h3psxskkb756offo3uznx4a44vuc5464mjkqwndyd.onion', 'Connection': 'keep-alive', 'Upgrade-Insecure-Requests': '1', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache'}
2023-10-08 10:49:05,610 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:87] - INFO: [GET METHOD] request url = http://deepmixjso4ero6h3psxskkb756offo3uznx4a44vuc5464mjkqwndyd.onion
2023-10-08 10:49:05,610 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:88] - INFO: [GET METHOD] request proxy = {'http': 'socks5h://admin:a7dm1n@45.32.223.200:65533', 'https': 'socks5h://admin:a7dm1n@45.32.223.200:65533'}
2023-10-08 10:49:05,610 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:89] - INFO: [GET METHOD] request params = None
2023-10-08 10:49:05,613 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:337] - INFO: parse domain is deepmixl6jyyextuekqvufhaw3k4fv2zygcllo5lciupwdru6cb7xeqd.onion, index_url is http://deepmixl6jyyextuekqvufhaw3k4fv2zygcllo5lciupwdru6cb7xeqd.onion
2023-10-08 10:49:05,613 - /Users/zhangmingming/pyProjects/vcrawl/handler/darnet/trading_net_handler.py[line:88] - INFO: step1: request enter url
2023-10-08 10:49:05,613 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:86] - INFO: [GET METHOD] headers is : {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'deepmixl6jyyextuekqvufhaw3k4fv2zygcllo5lciupwdru6cb7xeqd.onion', 'Connection': 'keep-alive', 'Upgrade-Insecure-Requests': '1', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache'}
2023-10-08 10:49:05,613 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:87] - INFO: [GET METHOD] request url = http://deepmixl6jyyextuekqvufhaw3k4fv2zygcllo5lciupwdru6cb7xeqd.onion
2023-10-08 10:49:05,613 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:88] - INFO: [GET METHOD] request proxy = {'http': 'socks5h://admin:a7dm1n@45.32.223.200:65533', 'https': 'socks5h://admin:a7dm1n@45.32.223.200:65533'}
2023-10-08 10:49:05,614 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:89] - INFO: [GET METHOD] request params = None
2023-10-08 10:49:05,617 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:137] - ERROR: 暗网中文网爬虫错误,异常信息:["暗网中文网使用域名xxxxxxxxss2wdceudprpxnmvjs5kwnlnfvun57koml6hkp6u7qwyhsyd.onion错误,异常信息:SOCKSHTTPConnectionPool(host='xxxxxxxxss2wdceudprpxnmvjs5kwnlnfvun57koml6hkp6u7qwyhsyd.onion', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7f8e3a46b750>: Failed to establish a new connection: [Errno 51] Network is unreachable'))", "暗网中文网使用域名xxxxxxxx3a3kuuhhw5w7stk25fzhttrlpiomij5bogkg7yyqsng5tqyd.onion错误,异常信息:SOCKSHTTPConnectionPool(host='xxxxxxxx3a3kuuhhw5w7stk25fzhttrlpiomij5bogkg7yyqsng5tqyd.onion', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7f8e3a499ad0>: Failed to establish a new connection: [Errno 51] Network is unreachable'))", "暗网中文网使用域名xxxxxxxxneal7wz6nk2tuquh54pruer5nfgwtsdw4c4xk6jc2swaidad.onion错误,异常信息:SOCKSHTTPConnectionPool(host='xxxxxxxxneal7wz6nk2tuquh54pruer5nfgwtsdw4c4xk6jc2swaidad.onion', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7f8e3a4a21d0>: Failed to establish a new connection: [Errno 51] Network is unreachable'))", "暗网中文网使用域名xxxxxxxxp56bqacrnumb4ouvxthknazytrz4hsxhth4mjnm3kihdtoyd.onion错误,异常信息:SOCKSHTTPConnectionPool(host='xxxxxxxxp56bqacrnumb4ouvxthknazytrz4hsxhth4mjnm3kihdtoyd.onion', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7f8e3a4ab510>: Failed to establish a new connection: [Errno 51] Network is unreachable'))", "暗网中文网使用域名xxxxxxxzxxbmwmggbeyt26t6nlgktj5le7crh4yat6ztfwqxn4uxvmad.onion错误,异常信息:SOCKSHTTPConnectionPool(host='xxxxxxxzxxbmwmggbeyt26t6nlgktj5le7crh4yat6ztfwqxn4uxvmad.onion', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7f8e3a4b4910>: Failed to establish a new connection: [Errno 51] Network is unreachable'))", "暗网中文网使用域名xxxxxxxxqeuwvkrsesijvfcem4dtkpm77srgru2vrvk7dvm4hur3ymid.onion错误,异常信息:SOCKSHTTPConnectionPool(host='xxxxxxxxqeuwvkrsesijvfcem4dtkpm77srgru2vrvk7dvm4hur3ymid.onion', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7f8e3a4abb50>: Failed to establish a new connection: [Errno 51] Network is unreachable'))", "暗网中文网使用域名deepmixaasic2p6vm6f4d4g52e4ve6t37ejtti4holhhkdsmq3jsf3id.onion错误,异常信息:SOCKSHTTPConnectionPool(host='deepmixaasic2p6vm6f4d4g52e4ve6t37ejtti4holhhkdsmq3jsf3id.onion', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7f8e3a4a2ad0>: Failed to establish a new connection: [Errno 51] Network is unreachable'))", "暗网中文网使用域名deepmixbf6xqt3m7kagmurdt4v43f2h3doc23h7hrkjlroovyjsvseqd.onion错误,异常信息:SOCKSHTTPConnectionPool(host='deepmixbf6xqt3m7kagmurdt4v43f2h3doc23h7hrkjlroovyjsvseqd.onion', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7f8e3a499690>: Failed to establish a new connection: [Errno 51] Network is unreachable'))", "暗网中文网使用域名deepmixjso4ero6h3psxskkb756offo3uznx4a44vuc5464mjkqwndyd.onion错误,异常信息:SOCKSHTTPConnectionPool(host='deepmixjso4ero6h3psxskkb756offo3uznx4a44vuc5464mjkqwndyd.onion', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7f8e3a4c17d0>: Failed to establish a new connection: [Errno 51] Network is unreachable'))", "暗网中文网使用域名deepmixl6jyyextuekqvufhaw3k4fv2zygcllo5lciupwdru6cb7xeqd.onion错误,异常信息:SOCKSHTTPConnectionPool(host='deepmixl6jyyextuekqvufhaw3k4fv2zygcllo5lciupwdru6cb7xeqd.onion', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7f8e3a4c1510>: Failed to establish a new connection: [Errno 51] Network is unreachable'))"]
2023-10-08 10:50:57,744 - /Users/zhangmingming/pyProjects/vcrawl/vcrawl_task.py[line:26] - INFO: crawl type is darknet_changan,run_type is once
2023-10-08 10:51:00,808 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:59] - INFO: jobconf=<tools.config_parser.CrawlConfigParser object at 0x7fa52801be10>
protocol=http
keywords=['建行', '建设银行', '银行', '信用卡', '贷款', '金融']
base_type=darknet
sub_type=changan
dtype=darknet_changan
alter_type=email
to_addrs=zhangchaoss122@163.com
error_addrs=zhangchaoss122@163.com
zh_type=长安不夜城
crux_key=
run_interval=1800
proxies={'http': 'socks5h://admin:a7dm1n@45.32.223.200:65533', 'https': 'socks5h://admin:a7dm1n@45.32.223.200:65533'}
tor_enable=True
firefox_binary=/Applications/Tor Browser.app/Contents/MacOS/firefox
geckodriver_path=/Users/zhangmingming/tool/geckodriver
headless=True
auth_header=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmUiOjE2ODY3MTYyNTUsImhpZCI6IjE0ODg0NDUxMiIsImxldmVsIjowfQ.PcL65QZArakxEYocBAw0DUixYL3ovWPSWYQGFdMgRkk
max_pagenum=10
query_path=api/category/goods
domain=cabyceogpsji73sske5nvo45mdrkbz4m3qd3iommf3zaaa6izg3j2cqd.onion
index_url=http://cabyceogpsji73sske5nvo45mdrkbz4m3qd3iommf3zaaa6izg3j2cqd.onion
username=mzzlimuzi
passwd=T@ianqi6997091
query_cookies_str_format=Bearer %s
task_id=1
2023-10-08 10:51:00,808 - /Users/zhangmingming/pyProjects/vcrawl/handler/cabyc/changan_handler.py[line:51] - INFO: 使用TOR浏览器登录
2023-10-08 10:51:00,808 - /Users/zhangmingming/pyProjects/vcrawl/tools/tor_tool.py[line:61] - INFO: init browser option
2023-10-08 10:51:05,739 - /Users/zhangmingming/pyProjects/vcrawl/tools/tor_tool.py[line:92] - INFO: close alert
2023-10-08 10:51:05,832 - /Users/zhangmingming/pyProjects/vcrawl/tools/tor_tool.py[line:101] - INFO: check page load complete
2023-10-08 10:53:59,602 - /Users/zhangmingming/pyProjects/vcrawl/vcrawl_task.py[line:26] - INFO: crawl type is darknet_changan,run_type is once
2023-10-08 10:53:59,603 - /Users/zhangmingming/pyProjects/vcrawl/handler/base_handler.py[line:59] - INFO: jobconf=<tools.config_parser.CrawlConfigParser object at 0x7fd2406bbfd0>
protocol=http
keywords=['建行', '建设银行', '银行', '信用卡', '贷款', '金融']
base_type=darknet
sub_type=changan
dtype=darknet_changan
alter_type=email
to_addrs=zhangchaoss122@163.com
error_addrs=zhangchaoss122@163.com
zh_type=长安不夜城
crux_key=
run_interval=1800
proxies={'http': 'socks5h://admin:a7dm1n@45.32.223.200:65533', 'https': 'socks5h://admin:a7dm1n@45.32.223.200:65533'}
tor_enable=True
firefox_binary=/Applications/Tor Browser.app/Contents/MacOS/firefox
geckodriver_path=/Users/zhangmingming/tool/geckodriver
headless=True
auth_header=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmUiOjE2ODY3MTYyNTUsImhpZCI6IjE0ODg0NDUxMiIsImxldmVsIjowfQ.PcL65QZArakxEYocBAw0DUixYL3ovWPSWYQGFdMgRkk
max_pagenum=10
query_path=api/category/goods
domain=cabyceogpsji73sske5nvo45mdrkbz4m3qd3iommf3zaaa6izg3j2cqd.onion
index_url=http://cabyceogpsji73sske5nvo45mdrkbz4m3qd3iommf3zaaa6izg3j2cqd.onion
username=mzzlimuzi
passwd=T@ianqi6997091
query_cookies_str_format=Bearer %s
task_id=1
2023-10-08 10:53:59,604 - /Users/zhangmingming/pyProjects/vcrawl/handler/cabyc/changan_handler.py[line:51] - INFO: 使用TOR浏览器登录
2023-10-08 10:53:59,604 - /Users/zhangmingming/pyProjects/vcrawl/tools/tor_tool.py[line:61] - INFO: init browser option
2023-10-08 10:54:01,744 - /Users/zhangmingming/pyProjects/vcrawl/tools/tor_tool.py[line:92] - INFO: close alert
2023-10-08 10:54:01,769 - /Users/zhangmingming/pyProjects/vcrawl/tools/tor_tool.py[line:101] - INFO: check page load complete
2023-10-08 11:16:18,914 - /Users/zhangmingming/pyProjects/vcrawl/tools/tor_tool.py[line:50] - ERROR: failed connect tor, retry connect
2023-10-08 11:16:18,915 - /Users/zhangmingming/pyProjects/vcrawl/venv/lib/python3.7/site-packages/retry/api.py[line:40] - WARNING: failed connect tor, retry connect, retrying in 10 seconds...
2023-10-08 11:16:28,920 - /Users/zhangmingming/pyProjects/vcrawl/tools/tor_tool.py[line:61] - INFO: init browser option
2023-10-08 11:16:31,106 - /Users/zhangmingming/pyProjects/vcrawl/tools/tor_tool.py[line:92] - INFO: close alert
2023-10-08 11:16:31,160 - /Users/zhangmingming/pyProjects/vcrawl/tools/tor_tool.py[line:101] - INFO: check page load complete
2023-10-08 11:17:00,199 - /Users/zhangmingming/pyProjects/vcrawl/vcrawl_task.py[line:41] - ERROR: once run error, error msg is 'ChangAn' object has no attribute 'driver' , msgTraceback (most recent call last):
  File "/Users/zhangmingming/pyProjects/vcrawl/handler/cabyc/changan_handler.py", line 56, in login_with_tor_headless
    self.headless)
  File "/Users/zhangmingming/pyProjects/vcrawl/venv/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/Users/zhangmingming/pyProjects/vcrawl/venv/lib/python3.7/site-packages/retry/api.py", line 74, in retry_decorator
    logger)
  File "/Users/zhangmingming/pyProjects/vcrawl/venv/lib/python3.7/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/Users/zhangmingming/pyProjects/vcrawl/tools/tor_tool.py", line 48, in connect_tor_with_retry
    driver = open_browser_with_headless(firefox_binary, geckodriver_path, proxies, headless)
  File "/Users/zhangmingming/pyProjects/vcrawl/tools/tor_tool.py", line 103, in open_browser_with_headless
    EC.element_to_be_clickable((By.CSS_SELECTOR, '.on'))
  File "/Users/zhangmingming/pyProjects/vcrawl/venv/lib/python3.7/site-packages/selenium/webdriver/support/wait.py", line 87, in until
    time.sleep(self._poll)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zhangmingming/pyProjects/vcrawl/vcrawl_task.py", line 34, in run
    handler_list[key](jobconf).run(id=task_id)
  File "/Users/zhangmingming/pyProjects/vcrawl/handler/cabyc/changan_handler.py", line 427, in run
    if not self.login_with_tor_headless():
  File "/Users/zhangmingming/pyProjects/vcrawl/handler/cabyc/changan_handler.py", line 62, in login_with_tor_headless
    if self.driver:
AttributeError: 'ChangAn' object has no attribute 'driver'

2023-10-08 11:18:33,083 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 11:21:54,539 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 11:21:57,163 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 11:21:59,428 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 11:22:41,933 - /Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_base.py[line:15] - INFO: crawl bootstrap_servers is 127.0.0.1:9092
2023-10-08 12:47:25,197 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 12:47:27,750 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 12:47:30,006 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 12:48:12,737 - /Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_base.py[line:15] - INFO: crawl bootstrap_servers is 127.0.0.1:9092
2023-10-08 13:40:25,741 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 13:40:43,704 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 13:40:46,001 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 13:41:12,518 - /Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_base.py[line:15] - INFO: crawl bootstrap_servers is 127.0.0.1:9092
2023-10-08 13:44:20,264 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 13:44:22,943 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 13:44:25,510 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 13:44:26,045 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:31] - ERROR: get_message run error, error msg is [Errno 45] Operation not supported: '/home/py', msg_trackback is Traceback (most recent call last):
  File "/Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py", line 27, in run
    tg_handler_list[action](self.session_file, self.app_conf).run(id=task_id)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 141, in run
    self.telegram_get_message()
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 60, in telegram_get_message
    message_res = self.ta.scan_message(chat_dialog, **param)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/common/telegramAPIs.py", line 351, in scan_message
    file_name = self.download_image(message)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/common/telegramAPIs.py", line 454, in download_image
    filename = self.client.download_media(message, self.image_path)
  File "/Users/zhangmingming/pyProjects/vcrawl/venv/lib/python3.7/site-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Users/zhangmingming/pyProjects/vcrawl/venv/lib/python3.7/site-packages/telethon/client/downloads.py", line 419, in download_media
    media, file, date, thumb, progress_callback
  File "/Users/zhangmingming/pyProjects/vcrawl/venv/lib/python3.7/site-packages/telethon/client/downloads.py", line 843, in _download_photo
    progress_callback=progress_callback
  File "/Users/zhangmingming/pyProjects/vcrawl/venv/lib/python3.7/site-packages/telethon/client/downloads.py", line 505, in download_file
    iv=iv,
  File "/Users/zhangmingming/pyProjects/vcrawl/venv/lib/python3.7/site-packages/telethon/client/downloads.py", line 539, in _download_file
    helpers.ensure_parent_dir_exists(file)
  File "/Users/zhangmingming/pyProjects/vcrawl/venv/lib/python3.7/site-packages/telethon/helpers.py", line 36, in ensure_parent_dir_exists
    os.makedirs(parent, exist_ok=True)
  File "/usr/local/bin/../../../Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/bin/../../../Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 45] Operation not supported: '/home/py'

2023-10-08 13:44:49,697 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 13:44:52,290 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 13:44:54,513 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 13:44:55,006 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:31] - ERROR: get_message run error, error msg is [Errno 45] Operation not supported: '/home/py', msg_trackback is Traceback (most recent call last):
  File "/Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py", line 27, in run
    tg_handler_list[action](self.session_file, self.app_conf).run(id=task_id)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 141, in run
    self.telegram_get_message()
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 60, in telegram_get_message
    message_res = self.ta.scan_message(chat_dialog, **param)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/common/telegramAPIs.py", line 351, in scan_message
    file_name = self.download_image(message)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/common/telegramAPIs.py", line 454, in download_image
    filename = self.client.download_media(message, self.image_path)
  File "/Users/zhangmingming/pyProjects/vcrawl/venv/lib/python3.7/site-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Users/zhangmingming/pyProjects/vcrawl/venv/lib/python3.7/site-packages/telethon/client/downloads.py", line 419, in download_media
    media, file, date, thumb, progress_callback
  File "/Users/zhangmingming/pyProjects/vcrawl/venv/lib/python3.7/site-packages/telethon/client/downloads.py", line 843, in _download_photo
    progress_callback=progress_callback
  File "/Users/zhangmingming/pyProjects/vcrawl/venv/lib/python3.7/site-packages/telethon/client/downloads.py", line 505, in download_file
    iv=iv,
  File "/Users/zhangmingming/pyProjects/vcrawl/venv/lib/python3.7/site-packages/telethon/client/downloads.py", line 539, in _download_file
    helpers.ensure_parent_dir_exists(file)
  File "/Users/zhangmingming/pyProjects/vcrawl/venv/lib/python3.7/site-packages/telethon/helpers.py", line 36, in ensure_parent_dir_exists
    os.makedirs(parent, exist_ok=True)
  File "/usr/local/bin/../../../Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/bin/../../../Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 45] Operation not supported: '/home/py'

2023-10-08 13:45:54,518 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 13:45:57,908 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 13:46:00,894 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 13:46:03,470 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:31] - ERROR: get_message run error, error msg is .//Users/zhangmingming/pyProjects/vcrawl/data/image/photo_2022-10-08_20-30-09.jpg, msg_trackback is Traceback (most recent call last):
  File "/Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py", line 27, in run
    tg_handler_list[action](self.session_file, self.app_conf).run(id=task_id)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 141, in run
    self.telegram_get_message()
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 60, in telegram_get_message
    message_res = self.ta.scan_message(chat_dialog, **param)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/common/telegramAPIs.py", line 351, in scan_message
    file_name = self.download_image(message)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/common/telegramAPIs.py", line 457, in download_image
    ocr_image.scan_cn_image(f'./{filename}')
  File "/Users/zhangmingming/pyProjects/vcrawl/ocr_handler/cnocr/ocr_base.py", line 22, in scan_cn_image
    res = ocr.ocr(image_path)
  File "/Users/zhangmingming/pyProjects/vcrawl/venv/lib/python3.7/site-packages/cnocr/cn_ocr.py", line 247, in ocr
    img = self._prepare_img(img_fp)
  File "/Users/zhangmingming/pyProjects/vcrawl/venv/lib/python3.7/site-packages/cnocr/cn_ocr.py", line 318, in _prepare_img
    raise FileNotFoundError(img_fp)
FileNotFoundError: .//Users/zhangmingming/pyProjects/vcrawl/data/image/photo_2022-10-08_20-30-09.jpg

2023-10-08 13:46:21,285 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 13:46:24,098 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 13:46:26,736 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 13:46:49,182 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 13:46:52,423 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 13:46:54,535 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 13:47:08,541 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 13:47:11,988 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 13:47:14,326 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 14:22:56,798 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 14:22:59,647 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 14:23:02,536 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 14:30:13,494 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 14:30:18,091 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 14:30:22,734 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 14:31:12,415 - /Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_base.py[line:15] - INFO: crawl bootstrap_servers is 127.0.0.1:9092
2023-10-08 15:18:25,067 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 15:18:27,350 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 15:18:29,516 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 15:19:26,728 - /Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_base.py[line:15] - INFO: crawl bootstrap_servers is 127.0.0.1:9092
2023-10-08 15:21:58,324 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 15:22:01,493 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 15:22:04,929 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 15:23:01,420 - /Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_base.py[line:15] - INFO: crawl bootstrap_servers is 127.0.0.1:9092
2023-10-08 15:24:35,798 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 15:24:38,326 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 15:24:40,747 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 15:25:17,783 - /Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_base.py[line:15] - INFO: crawl bootstrap_servers is 127.0.0.1:9092
2023-10-08 15:25:17,792 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:31] - ERROR: get_message run error, error msg is the JSON object must be str, bytes or bytearray, not dict, msg_trackback is Traceback (most recent call last):
  File "/Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py", line 27, in run
    tg_handler_list[action](self.session_file, self.app_conf).run(id=task_id)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 141, in run
    self.telegram_get_message()
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 63, in telegram_get_message
    last_message_id_tmp = self.print_res(message_res)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 94, in print_res
    self.send_kafka_producer(data, tg_type)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_base.py", line 75, in send_kafka_producer
    crawler_producer.async_producer(result_scan_mes_json)
  File "/Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_producer.py", line 74, in async_producer
    data_json = json.loads(data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict

2023-10-08 15:27:19,218 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 15:27:22,055 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 15:27:24,559 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 15:28:04,566 - /Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_base.py[line:15] - INFO: crawl bootstrap_servers is 127.0.0.1:9092
2023-10-08 15:28:04,572 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:31] - ERROR: get_message run error, error msg is Expecting value: line 1 column 325 (char 324), msg_trackback is Traceback (most recent call last):
  File "/Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py", line 27, in run
    tg_handler_list[action](self.session_file, self.app_conf).run(id=task_id)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 141, in run
    self.telegram_get_message()
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 63, in telegram_get_message
    last_message_id_tmp = self.print_res(message_res)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 94, in print_res
    self.send_kafka_producer(data, tg_type)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_base.py", line 75, in send_kafka_producer
    crawler_producer.async_producer(result_scan_mes_json)
  File "/Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_producer.py", line 74, in async_producer
    dic_str = json.loads(str(data).replace("'", "\""))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 325 (char 324)

2023-10-08 15:28:44,212 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 15:28:47,390 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 15:28:56,573 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 15:28:58,823 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 15:29:01,274 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 15:29:38,213 - /Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_base.py[line:15] - INFO: crawl bootstrap_servers is 127.0.0.1:9092
2023-10-08 15:30:03,299 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:31] - ERROR: get_message run error, error msg is Expecting property name enclosed in double quotes: line 1 column 2 (char 1), msg_trackback is Traceback (most recent call last):
  File "/Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py", line 27, in run
    tg_handler_list[action](self.session_file, self.app_conf).run(id=task_id)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 141, in run
    self.telegram_get_message()
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 63, in telegram_get_message
    last_message_id_tmp = self.print_res(message_res)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 94, in print_res
    self.send_kafka_producer(data, tg_type)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_base.py", line 75, in send_kafka_producer
    crawler_producer.async_producer(result_scan_mes_json)
  File "/Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_producer.py", line 74, in async_producer
    dic_str = json.loads(str(data))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

2023-10-08 15:31:04,904 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 15:31:09,481 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 15:31:13,891 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 15:31:52,041 - /Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_base.py[line:15] - INFO: crawl bootstrap_servers is 127.0.0.1:9092
2023-10-08 15:31:56,758 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:31] - ERROR: get_message run error, error msg is 'DateEncoder' object has no attribute 'decode', msg_trackback is Traceback (most recent call last):
  File "/Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py", line 27, in run
    tg_handler_list[action](self.session_file, self.app_conf).run(id=task_id)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 141, in run
    self.telegram_get_message()
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 63, in telegram_get_message
    last_message_id_tmp = self.print_res(message_res)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 94, in print_res
    self.send_kafka_producer(data, tg_type)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_base.py", line 75, in send_kafka_producer
    crawler_producer.async_producer(result_scan_mes_json)
  File "/Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_producer.py", line 74, in async_producer
    dic_str = json.loads(str(data), cls=DateEncoder)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 361, in loads
    return cls(**kw).decode(s)
AttributeError: 'DateEncoder' object has no attribute 'decode'

2023-10-08 15:33:35,834 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 15:33:38,546 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 15:33:41,436 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 15:34:28,123 - /Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_base.py[line:15] - INFO: crawl bootstrap_servers is 127.0.0.1:9092
2023-10-08 15:35:52,112 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 15:35:55,173 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 15:35:59,364 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 15:38:02,912 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 15:38:06,111 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 15:38:10,657 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 15:41:09,644 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 15:41:13,798 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 15:41:16,924 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 15:41:55,897 - /Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_base.py[line:15] - INFO: crawl bootstrap_servers is 127.0.0.1:9092
2023-10-08 15:42:21,976 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 15:42:26,145 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 15:42:29,161 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 15:43:13,303 - /Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_base.py[line:15] - INFO: crawl bootstrap_servers is 127.0.0.1:9092
2023-10-08 15:46:32,245 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 15:46:34,870 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 15:46:38,150 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 15:47:14,842 - /Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_base.py[line:15] - INFO: crawl bootstrap_servers is 127.0.0.1:9092
2023-10-08 15:47:27,692 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:31] - ERROR: get_message run error, error msg is Object of type datetime is not JSON serializable, msg_trackback is Traceback (most recent call last):
  File "/Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py", line 27, in run
    tg_handler_list[action](self.session_file, self.app_conf).run(id=task_id)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 141, in run
    self.telegram_get_message()
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 63, in telegram_get_message
    last_message_id_tmp = self.print_res(message_res)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 94, in print_res
    self.send_kafka_producer(data, tg_type)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_base.py", line 75, in send_kafka_producer
    crawler_producer.async_producer(result_scan_mes_json)
  File "/Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_producer.py", line 73, in async_producer
    data_json = json.dumps(data, ensure_ascii=False)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable

2023-10-08 15:48:10,617 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 15:48:15,020 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 15:48:18,593 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 15:49:12,635 - /Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_base.py[line:15] - INFO: crawl bootstrap_servers is 127.0.0.1:9092
2023-10-08 15:50:12,427 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 15:50:15,744 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 15:50:18,960 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 15:50:54,216 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 15:50:57,363 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 15:50:59,888 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 15:51:35,996 - /Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_base.py[line:15] - INFO: crawl bootstrap_servers is 127.0.0.1:9092
2023-10-08 15:51:43,150 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:31] - ERROR: get_message run error, error msg is Object of type bytes is not JSON serializable, msg_trackback is Traceback (most recent call last):
  File "/Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py", line 27, in run
    tg_handler_list[action](self.session_file, self.app_conf).run(id=task_id)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 141, in run
    self.telegram_get_message()
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 63, in telegram_get_message
    last_message_id_tmp = self.print_res(message_res)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 94, in print_res
    self.send_kafka_producer(data, tg_type)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_base.py", line 75, in send_kafka_producer
    crawler_producer.async_producer(result_scan_mes_json)
  File "/Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_producer.py", line 85, in async_producer
    self.__producer.send(self.topic, value=data_json.encode('GBK'))
  File "/Users/zhangmingming/pyProjects/vcrawl/venv/lib/python3.7/site-packages/kafka/producer/kafka.py", line 583, in send
    topic, value)
  File "/Users/zhangmingming/pyProjects/vcrawl/venv/lib/python3.7/site-packages/kafka/producer/kafka.py", line 714, in _serialize
    return f(data)
  File "/Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_producer.py", line 38, in <lambda>
    value_serializer=lambda m: json.dumps(m).encode('ascii'), request_timeout_ms=60000,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable

2023-10-08 15:51:58,424 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 15:52:00,984 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 15:52:03,319 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 15:57:00,812 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 15:57:03,881 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 15:57:07,370 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 15:57:50,625 - /Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_base.py[line:15] - INFO: crawl bootstrap_servers is 127.0.0.1:9092
2023-10-08 15:58:03,507 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:31] - ERROR: get_message run error, error msg is Object of type bytes is not JSON serializable, msg_trackback is Traceback (most recent call last):
  File "/Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py", line 27, in run
    tg_handler_list[action](self.session_file, self.app_conf).run(id=task_id)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 141, in run
    self.telegram_get_message()
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 63, in telegram_get_message
    last_message_id_tmp = self.print_res(message_res)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 94, in print_res
    self.send_kafka_producer(data, tg_type)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_base.py", line 75, in send_kafka_producer
    crawler_producer.async_producer(result_scan_mes_json)
  File "/Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_producer.py", line 85, in async_producer
    self.__producer.send(self.topic, value=data_json.encode('GBK'))
  File "/Users/zhangmingming/pyProjects/vcrawl/venv/lib/python3.7/site-packages/kafka/producer/kafka.py", line 583, in send
    topic, value)
  File "/Users/zhangmingming/pyProjects/vcrawl/venv/lib/python3.7/site-packages/kafka/producer/kafka.py", line 714, in _serialize
    return f(data)
  File "/Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_producer.py", line 38, in <lambda>
    value_serializer=lambda m: json.dumps(m).encode('utf-8'), request_timeout_ms=60000,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable

2023-10-08 15:58:27,667 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 15:58:30,516 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 15:58:32,999 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 15:59:16,920 - /Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_base.py[line:15] - INFO: crawl bootstrap_servers is 127.0.0.1:9092
2023-10-08 16:06:04,122 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 16:06:07,073 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 16:06:10,200 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 16:06:47,551 - /Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_base.py[line:15] - INFO: crawl bootstrap_servers is 127.0.0.1:9092
2023-10-08 16:09:25,590 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 16:09:27,764 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 16:09:30,032 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 16:10:07,452 - /Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_base.py[line:15] - INFO: crawl bootstrap_servers is 127.0.0.1:9092
2023-10-08 16:10:36,173 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 16:10:38,647 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 16:10:40,880 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 16:12:00,623 - /Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_base.py[line:15] - INFO: crawl bootstrap_servers is 127.0.0.1:9092
2023-10-08 16:12:49,714 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 16:12:52,437 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 16:12:55,471 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 16:13:35,406 - /Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_base.py[line:15] - INFO: crawl bootstrap_servers is 127.0.0.1:9092
2023-10-08 16:15:10,174 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 16:15:12,637 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 16:15:15,123 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 16:16:02,638 - /Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_base.py[line:15] - INFO: crawl bootstrap_servers is 127.0.0.1:9092
2023-10-08 16:18:14,520 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 16:18:20,193 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 16:18:22,447 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 16:18:59,994 - /Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_base.py[line:15] - INFO: crawl bootstrap_servers is 127.0.0.1:9092
2023-10-08 16:19:07,159 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:31] - ERROR: get_message run error, error msg is , msg_trackback is Traceback (most recent call last):
  File "/Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py", line 27, in run
    tg_handler_list[action](self.session_file, self.app_conf).run(id=task_id)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 141, in run
    self.telegram_get_message()
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 63, in telegram_get_message
    last_message_id_tmp = self.print_res(message_res)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 94, in print_res
    self.send_kafka_producer(data, tg_type)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_base.py", line 75, in send_kafka_producer
    crawler_producer.async_producer(result_scan_mes_json)
  File "/Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_producer.py", line 87, in async_producer
    self.__producer.send(self.topic, value=json_data_without_slash)
  File "/Users/zhangmingming/pyProjects/vcrawl/venv/lib/python3.7/site-packages/kafka/producer/kafka.py", line 585, in send
    assert type(value_bytes) in (bytes, bytearray, memoryview, type(None))
AssertionError

2023-10-08 16:20:55,063 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 16:20:57,441 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 16:20:59,940 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 16:21:38,550 - /Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_base.py[line:15] - INFO: crawl bootstrap_servers is 127.0.0.1:9092
2023-10-08 16:23:38,037 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 16:23:41,028 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 16:23:43,431 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 16:24:28,798 - /Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_base.py[line:15] - INFO: crawl bootstrap_servers is 127.0.0.1:9092
2023-10-08 16:27:59,323 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 16:28:02,018 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 16:28:05,508 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 16:28:45,362 - /Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_base.py[line:15] - INFO: crawl bootstrap_servers is 127.0.0.1:9092
2023-10-08 16:31:02,633 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 16:31:05,221 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 16:31:07,767 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 16:31:44,701 - /Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_base.py[line:15] - INFO: crawl bootstrap_servers is 127.0.0.1:9092
2023-10-08 16:31:58,468 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:31] - ERROR: get_message run error, error msg is , msg_trackback is Traceback (most recent call last):
  File "/Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py", line 27, in run
    tg_handler_list[action](self.session_file, self.app_conf).run(id=task_id)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 141, in run
    self.telegram_get_message()
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 63, in telegram_get_message
    last_message_id_tmp = self.print_res(message_res)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 94, in print_res
    self.send_kafka_producer(data, tg_type)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_base.py", line 75, in send_kafka_producer
    crawler_producer.async_producer(result_scan_mes_json)
  File "/Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_producer.py", line 72, in async_producer
    self.__producer.send(self.topic, value=str(data))
  File "/Users/zhangmingming/pyProjects/vcrawl/venv/lib/python3.7/site-packages/kafka/producer/kafka.py", line 585, in send
    assert type(value_bytes) in (bytes, bytearray, memoryview, type(None))
AssertionError

2023-10-08 16:32:35,393 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 16:32:37,956 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 16:32:40,502 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 16:33:16,621 - /Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_base.py[line:15] - INFO: crawl bootstrap_servers is 127.0.0.1:9092
2023-10-08 16:34:00,401 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 16:34:04,022 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 16:34:08,577 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 16:34:51,781 - /Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_base.py[line:15] - INFO: crawl bootstrap_servers is 127.0.0.1:9092
2023-10-08 16:46:27,016 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 16:46:33,648 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 16:46:36,195 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 16:48:06,441 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 16:48:08,795 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 16:48:11,076 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 17:13:13,126 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 17:13:16,043 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 17:13:18,795 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 17:31:27,346 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 17:31:33,178 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 17:31:36,587 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 17:32:28,638 - /Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_base.py[line:15] - INFO: crawl bootstrap_servers is 127.0.0.1:9092
2023-10-08 17:33:18,030 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 17:33:22,795 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 17:33:25,185 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 17:33:55,545 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 17:33:58,311 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 17:34:01,069 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 17:37:45,216 - /Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_base.py[line:15] - INFO: crawl bootstrap_servers is 127.0.0.1:9092
2023-10-08 17:41:02,225 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 17:41:04,940 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 17:41:07,572 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 17:41:50,531 - /Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_base.py[line:15] - INFO: crawl bootstrap_servers is 127.0.0.1:9092
2023-10-08 18:46:03,576 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 18:50:44,316 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 18:50:47,883 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 18:56:37,053 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 18:56:39,449 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 18:56:42,131 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 18:57:23,493 - /Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_base.py[line:15] - INFO: crawl bootstrap_servers is 127.0.0.1:9092
2023-10-08 19:26:07,617 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 19:26:10,585 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 19:26:12,913 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 19:26:12,931 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:31] - ERROR: get_message run error, error msg is '>' not supported between instances of 'int' and 'str', msg_trackback is Traceback (most recent call last):
  File "/Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py", line 27, in run
    tg_handler_list[action](self.session_file, self.app_conf).run(id=task_id)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 143, in run
    self.telegram_get_message()
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 51, in telegram_get_message
    while (now_tmp > self.publish_time):
TypeError: '>' not supported between instances of 'int' and 'str'

2023-10-08 19:26:34,308 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 19:26:40,965 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 19:26:43,942 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 19:27:24,924 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 19:27:31,179 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 19:27:34,656 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 19:30:28,255 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 19:30:32,679 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 19:30:37,138 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 19:30:48,625 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:31] - ERROR: get_message run error, error msg is '>' not supported between instances of 'int' and 'str', msg_trackback is Traceback (most recent call last):
  File "/Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py", line 27, in run
    tg_handler_list[action](self.session_file, self.app_conf).run(id=task_id)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 143, in run
    self.telegram_get_message()
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 51, in telegram_get_message
    while (now_tmp > self.publish_time):
TypeError: '>' not supported between instances of 'int' and 'str'

2023-10-08 19:30:59,131 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 19:31:03,905 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 19:31:06,856 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 19:31:17,918 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:31] - ERROR: get_message run error, error msg is '>' not supported between instances of 'int' and 'str', msg_trackback is Traceback (most recent call last):
  File "/Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py", line 27, in run
    tg_handler_list[action](self.session_file, self.app_conf).run(id=task_id)
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 143, in run
    self.telegram_get_message()
  File "/Users/zhangmingming/pyProjects/vcrawl/tg_spiders/cli/telegram_get_message.py", line 51, in telegram_get_message
    while (now_tmp > self.publish_time):
TypeError: '>' not supported between instances of 'int' and 'str'

2023-10-08 19:31:53,878 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 19:31:57,312 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 19:32:03,939 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 19:32:06,339 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 19:32:08,699 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 19:45:32,077 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 19:45:35,730 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 19:45:39,077 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 19:45:39,087 - /Users/zhangmingming/pyProjects/vcrawl/tools/log.py[line:61] - ERROR: <Model: TgGroupModel> instance matching query does not exist:
SQL: SELECT `t1`.`id`, `t1`.`channel_id`, `t1`.`tenant_id`, `t1`.`title`, `t1`.`username`, `t1`.`hex_url`, `t1`.`offset_date`, `t1`.`megagroup`, `t1`.`member_count`, `t1`.`channel_description`, `t1`.`last_message_id`, `t1`.`is_public`, `t1`.`join_date`, `t1`.`create_time`, `t1`.`update_time` FROM `tg_channel_group` AS `t1` WHERE (`t1`.`username` = %s) LIMIT %s OFFSET %s
Params: ['xliluo', 1, 0]
Traceback (most recent call last):
  File "/Users/zhangmingming/pyProjects/vcrawl/venv/lib/python3.7/site-packages/peewee.py", line 7048, in get
    return clone.execute(database)[0]
  File "/Users/zhangmingming/pyProjects/vcrawl/venv/lib/python3.7/site-packages/peewee.py", line 4413, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zhangmingming/pyProjects/vcrawl/tools/log.py", line 59, in wrapper
    return func(*args, **kwargs)
  File "/Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py", line 54, in channel_group_detail_id
    TgGroupModel.username == user_name
  File "/Users/zhangmingming/pyProjects/vcrawl/venv/lib/python3.7/site-packages/peewee.py", line 6600, in get
    return sq.get()
  File "/Users/zhangmingming/pyProjects/vcrawl/venv/lib/python3.7/site-packages/peewee.py", line 7053, in get
    (clone.model, sql, params))
mapper.model.tg_group_model.TgGroupModelDoesNotExist: <Model: TgGroupModel> instance matching query does not exist:
SQL: SELECT `t1`.`id`, `t1`.`channel_id`, `t1`.`tenant_id`, `t1`.`title`, `t1`.`username`, `t1`.`hex_url`, `t1`.`offset_date`, `t1`.`megagroup`, `t1`.`member_count`, `t1`.`channel_description`, `t1`.`last_message_id`, `t1`.`is_public`, `t1`.`join_date`, `t1`.`create_time`, `t1`.`update_time` FROM `tg_channel_group` AS `t1` WHERE (`t1`.`username` = %s) LIMIT %s OFFSET %s
Params: ['xliluo', 1, 0]
2023-10-08 19:45:39,092 - /Users/zhangmingming/pyProjects/vcrawl/service/tg_group_model_service.py[line:17] - INFO: 没有频道数据信息
2023-10-08 19:47:45,024 - /Users/zhangmingming/pyProjects/vcrawl/task/tg_crawl_task.py[line:22] - INFO: tg tg type is get_message,task_id is 1
2023-10-08 19:47:48,305 - /Users/zhangmingming/pyProjects/vcrawl/mapper/monitor_task_dao.py[line:30] - INFO: task_id is 1 
2023-10-08 19:47:50,610 - /Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py[line:52] - INFO: channel_id is xliluo 
2023-10-08 19:47:50,624 - /Users/zhangmingming/pyProjects/vcrawl/tools/log.py[line:61] - ERROR: <Model: TgGroupModel> instance matching query does not exist:
SQL: SELECT `t1`.`id`, `t1`.`channel_id`, `t1`.`tenant_id`, `t1`.`title`, `t1`.`username`, `t1`.`hex_url`, `t1`.`offset_date`, `t1`.`megagroup`, `t1`.`member_count`, `t1`.`channel_description`, `t1`.`last_message_id`, `t1`.`is_public`, `t1`.`join_date`, `t1`.`create_time`, `t1`.`update_time` FROM `tg_channel_group` AS `t1` WHERE (`t1`.`username` = %s) LIMIT %s OFFSET %s
Params: ['xliluo', 1, 0]
Traceback (most recent call last):
  File "/Users/zhangmingming/pyProjects/vcrawl/venv/lib/python3.7/site-packages/peewee.py", line 7048, in get
    return clone.execute(database)[0]
  File "/Users/zhangmingming/pyProjects/vcrawl/venv/lib/python3.7/site-packages/peewee.py", line 4413, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zhangmingming/pyProjects/vcrawl/tools/log.py", line 59, in wrapper
    return func(*args, **kwargs)
  File "/Users/zhangmingming/pyProjects/vcrawl/mapper/tg_channel_group_dao.py", line 54, in channel_group_detail_id
    TgGroupModel.username == user_name
  File "/Users/zhangmingming/pyProjects/vcrawl/venv/lib/python3.7/site-packages/peewee.py", line 6600, in get
    return sq.get()
  File "/Users/zhangmingming/pyProjects/vcrawl/venv/lib/python3.7/site-packages/peewee.py", line 7053, in get
    (clone.model, sql, params))
mapper.model.tg_group_model.TgGroupModelDoesNotExist: <Model: TgGroupModel> instance matching query does not exist:
SQL: SELECT `t1`.`id`, `t1`.`channel_id`, `t1`.`tenant_id`, `t1`.`title`, `t1`.`username`, `t1`.`hex_url`, `t1`.`offset_date`, `t1`.`megagroup`, `t1`.`member_count`, `t1`.`channel_description`, `t1`.`last_message_id`, `t1`.`is_public`, `t1`.`join_date`, `t1`.`create_time`, `t1`.`update_time` FROM `tg_channel_group` AS `t1` WHERE (`t1`.`username` = %s) LIMIT %s OFFSET %s
Params: ['xliluo', 1, 0]
2023-10-08 19:47:50,629 - /Users/zhangmingming/pyProjects/vcrawl/service/tg_group_model_service.py[line:17] - INFO: 没有频道数据信息
2023-10-08 19:48:55,878 - /Users/zhangmingming/pyProjects/vcrawl/kafka_util/kafka_base.py[line:15] - INFO: crawl bootstrap_servers is 127.0.0.1:9092
